sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace


env:
  global:
    secure: "L84XVI6LuBkUDHAOLE/3Of/3+BRYI1DwxPyXnaJk7NNiW40sph721opj5TSIC7FNwmATwsCMiu9CihoVW3OW+DDI+xoKLmQpvV/buYkfWONAYoatpFuKOoHokMirh/ciFxn5hBwLYqVtY95yqs3ASGDt0jw2+kevQsS6Gu7NlkwKgLU1zuGoz6xKYBcvNeR1rYcg72oLiKYJF0RbvDnfK3EGgo83lDaEubqemHJsOfu5WagMLF62f/4PPZK6dZ3GWqDEmaVehMjJleP79Jtj+8SETAkPg75hEIoyHBXtLMrCWEk18CRkhoLhTqIBPOg4Kwloq863BjQQsbL7edSIACMM3cA1y2XCW2Jaeq3nKfjY3xJ1cj8DUW4GO5P2tj9S+WijZn+HHhAyUomLOXpzxk9zH0GEzYhaUvuui/67pC1+sq0ZPBE2BURAJGgE01i+0QhDMg4FXbrgPgobXzG11f7Dhsx0WlAwguLpaqAq88aINM0fy6zRrrBbx1rIf4EPcxDRkGbhkLk3Y2ZEtr3VP+eYBhP9+LbpZGYVa9lB2dahNRXGe4z5vMxscok0E2RCvPsetDr1d02gNRbLjrWuwoYyAse2/HcNB8WbV7Uti3SXS7qZEww6AKKmZgSfj+km/rNZVCUWJM89ZYFfLPwH/uWeXhya0O3dPps/2ZVZqY8="
branches:
  only:
    - master
